travis:
  secure:
    BINSTAR_TOKEN: HUJiOIOvUswjYzAtt6Re1jaNAEg7T+3wXBQ5YsaburzkM8P2gDpU5pAMbMxntt4BTOg9wc0qtSHp9MIKRzbPos0czSBkwV3S0hxUF5jy2wr2+lVyU1rAytFV1Lcpgwi2BrZdTkZt+6IaznvLuvoPK35A13cKprW7mk2TUz9MoRxR5KUH6x1BHHmxk1LFWO9tx1oL/BO0C5kTcFZKBgDZqW0IRb+JN9BhqZbfj9zpV9j11Td7l6P8H4EocRyvnB3TAeaq01vhzfFf3/TXy9lP7z3nJ1HuJRqMQZqlEMA3LvShg8qpxVOD1TYJQzvaOwTuO8PGYzdDJGdw8sobOqg0b3+PsKMwHAWCo34E2riU1t9hviroONJ7DFRy9gE/YstKLdO1D3S99JYIx5jpbeHs4VaxAY9zgKpfAR8Nij+vqY/qFhfV2H9u7D/EvAePduA64ZVW57jYjMEz+PoXtugk+xKpt1i09c240VjK4sGWBMjZhR1XgPCwOoaLtgvURZj5Cv7Rj3KjuDnqfzEhJ75tIis+ll2GIDQETIov4XE9/VWj8+5j4PDrMcAuMw6e4T0RkWrlRqBRDMLvyVisXv6l3IlbnBnJdBSFCcHFNwLrrLkAeAkns7zoq6OYzlTIM8+5TOZVKLImJCIg1gm6DRCaTAHMzoFzlg5RxTtb4UR2uTo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
